trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  solution: 'src/RoslynPad.sln'
  buildConfiguration: 'Release'

steps:
  - task: MSBuild@1
    inputs:
      solution: '$(solution)'
      msbuildArguments: '/t:Restore'
    displayName: Restore

  - task: MSBuild@1
    inputs:
      configuration: '$(buildConfiguration)'
      solution: '$(solution)'
      msbuildArguments: '/bl'
    displayName: Build

