trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  solution: 'src/RoslynPad.sln'
  buildConfiguration: 'Release'

steps:
- script: msbuild /t:restore '$(solution)'
  displayName: Restore
- script: msbuild /m /bl /p:Configuration=$(buildConfiguration '$(solution)'
  displayName: Build
